- name: Configure Server
  hosts: servers
  become: true
  vars_files:
    - vars.yml

  roles:
    - role: base
      tags: base
    - role: ssh
      tags: ssh
    - role: nginx
      tags: nginx
    - role: app
      tags: app